packages:
  - bot
allowBuilds:
  '@tensorflow/tfjs-node': set this to true or false
  better-sqlite3: true
  core-js: set this to true or false
  msgpackr-extract: set this to true or false
overrides:
  glob: 11.1.0
  cross-spawn: 7.0.5
  axios: ^1.9.0
  tar: ^7.5.11
  vite: ^8.0.10
